### ISSUE TITLE
wrong parse code

### ISSUE THREAD

**Issue by ButasButora** [xremix/SwiftGS1Barcode#25]
Hello,
I discovered another error where correct parsing does not occur. From code: 0105600360015567172409307149908319 10J051P0171081P 210RP7FW9KXP - 
![909b3635-3f27-45b8-8fb1-866bd9ca99eb](https://user-images.githubusercontent.com/61453828/193083977-7a598b76-3296-47d7-8ea4-c146c0d9c252.jpg)
only the PC was read correctly, the rest of the parameters unfortunately not anymore. Can I ask for some advice?

**Comment by xremix** [comment]
@ButasButora thanks for reaching out. The reason is simply, that the barcode contains application identifiers, that have not been implemented yet. I opened #26 which implements the NHRN for AIM, which you are using here.

I didn't push this to production yet and will add a couple of enhancements. But please feel free to extend the library with your own application identifiers that you need.

**Comment by ButasButora** [comment]
can you give me an example how to set this up? For example, even for values from this code?
Thanks a lot.

**Comment by xremix** [comment]
Yes totally (and please feel free to update this projects documentation, if you think steps are missing).

In this file, there are all AIs (application identifiers) setup:
https://github.com/xremix/SwiftGS1Barcode/blob/master/SwiftGS1Barcode/GS1Barcode.swift

If something you need is missing, you can find a list of all specified in the GS1 standard in here:
https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf
(I suggest you start reading from page 150)

Then you "simply" add the AI like I did in line 51 and 90:
https://github.com/xremix/SwiftGS1Barcode/pull/26/files#diff-64646fb6cdc9e73591117a6e130abcf9bc5ee6dabf1d23830ec7e3cd16358ead

Does this make any sense? I hope I described it well.

**Comment by xremix** [comment]
@ButasButora I added the AI to the library. Also, I implemented some code in #26 that unknown AIs get ignore until the next Group Separator. Which means, in your sample, it would ignore the AI 714, but would show 17, 01, 10 and 21 correct.

**Comment by ButasButora** [comment]
You are a god! I used the last pull request modification and the parsing is already running correctly!
thank you

**Comment by xremix** [comment]
Whoop whoop! You got lucky that I had a moment, right when you opened the PR :-)
